[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_22']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci',
]

[phases.build]
cmds = [
    'npm run build',
    'mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache',
    'chmod -R 775 storage bootstrap/cache',
]

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --class=MedalSeeder --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'

